version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  publish:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Set up Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install jq
          command: sudo apt-get install -y jq

      - run:
          name: Configure npm authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          environment:
            NPM_TOKEN: $NPM_TOKEN

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build the npm package
          command: npm run build

      - run:
          name: Publish to npm
          command: |
            VERSION=$(jq -r '.version' package.json)
            echo "Publishing version: $VERSION"
            npm publish --access public
          environment:
            NODE_AUTH_TOKEN: $NPM_TOKEN

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
