version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  publish:
    executor: node-executor
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Fetch all tags
          command: |
            cd ~/project
            git fetch --all --tags

      - run:
          name: Extract version from tag
          command: |
            cd ~/project
            TAG_NAME=$(git describe --tags --abbrev=0)
            echo "Extracted tag name: $TAG_NAME"
            VERSION=${TAG_NAME}
            echo "Setting npm version to: $VERSION"
            npm version $VERSION --no-git-tag-version

      - run:
          name: Set up Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Configure npm authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          environment:
            NPM_TOKEN: $NPM_TOKEN

      - run:
          name: Set git credentials
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "circleci+${CIRCLE_USERNAME}@users.noreply.github.com"
          environment:
            CIRCLE_USERNAME: $CIRCLE_USERNAME

      - run:
          name: Install dependencies
          command: |
            cd ~/project
            npm install

      - run:
          name: Build the npm package
          command: |
            cd ~/project
            npm run npm:package

      - run:
          name: Publish to npm
          command: |
            cd ~/project
            npm publish --access public
          environment:
            NODE_AUTH_TOKEN: $NPM_TOKEN

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
